apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: argo-test-0801
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: argo-test-0801 
  name: argo-test-0801
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: argo-test-0801 
    weight: 100 
  wildcardPolicy: None
