apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: argo-test-0801
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: argo-test-0801 
  name: argo-test-0801
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: argo-test-0801 
